services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - data_volume:/fastAPI/docs
    command: uvicorn main:app --host 0.0.0.0 --port 9000 --reload
#    depends_on:
#      - rabbitmq

#  celery:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - rabbitmq
#    command: celery -A tasks worker --concurrency=12 --loglevel=info
#    volumes:
#      - data_volume:/fastAPI/docs
#
#  rabbitmq:
#    image: rabbitmq:3-management
#    ports:
#      - "5672:5672"
#      - "15672:15672"

volumes:
  data_volume: